language: python
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
python:
  - "2.7"
  - "3.5"
before_install:
  - pip install -U pip
  - pip install wheel
# command to install dependencies
install:
  - pip wheel numpy
  - pip install --user-wheel numpy
  - pip install cython
  - pip install .
# command to run tests
# script: nosetests